### ISSUE TITLE
lxml.html.clean module is now a separate project lxml_html_clean

### ISSUE THREAD

**Issue by Nykakin** [zytedata/clear-html#3]
Looks like LXML version 5.2.0  broke imports here. I've got following log:
```python
Traceback (most recent call last):
  File "/home/runner/work/majornetlocs/majornetlocs/bin/check_po_requirements.py", line 8, in <module>
    consume_modules("majornetlocs.page_objects")
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/web_poet/rules.py", line 452, in consume_modules
    deque(gen, maxlen=0)
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/web_poet/rules.py", line 408, in _walk_module
    mod = importlib.import_module(spec.name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/runner/work/majornetlocs/majornetlocs/majornetlocs/page_objects/__init__.py", line 8, in <module>
    from zyte_common_items import ProductNavigationPage
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/zyte_common_items/__init__.py", line 45, in <module>
    from .extractors import (
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/zyte_common_items/extractors.py", line 4, in <module>
    from .processors import gtin_processor, price_processor, simple_price_processor
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/zyte_common_items/processors.py", line 5, in <module>
    from clear_html import clean_node, cleaned_node_to_html, cleaned_node_to_text
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/clear_html/__init__.py", line 2, in <module>
    from .clean import clean_node, cleaned_node_to_html, cleaned_node_to_text  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/clear_html/clean.py", line 4, in <module>
    import html_text
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/html_text/__init__.py", line 4, in <module>
    from .html_text import (etree_to_text, extract_text, selector_to_text,
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/html_text/html_text.py", line 6, in <module>
    from lxml.html.clean import Cleaner
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.
```

**Comment by wRAR** [comment]
This should be fixed with html-text 0.6.0.
